### ISSUE TITLE
Image for sewer exit in Whittleton creek (both missions) not loading

### ISSUE THREAD

**Issue by leonardoparga** [BRYN4444/HitmanRoulette#2]
The image for the Sewer/manhole exit in both "A new life" and "A bitter pill" is not loading. 

Should be an easy fix, changing the name of the exit to Manhole to match the css classes, or changing the name of the css classes to Sewer to match the name of the exit.

**Comment by BRYN4444** [comment]
Thanks for letting me know! I renamed the files and CSS, but missed it in the data itself. Oops!
